### ISSUE TITLE
`patchChangelog` fails with Dokka to 1.7.20

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [JetBrains/gradle-changelog-plugin#131]
**Describe the bug**
After updating Dokka to 1.7.20, running `patchChangelog` fails with

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':patchChangelog'.
...
Caused by: java.lang.NoSuchMethodError: 'void org.intellij.markdown.parser.MarkdownParser.<init>(org.intellij.markdown.flavours.MarkdownFlavourDescriptor)'
	at org.jetbrains.changelog.Changelog.<init>(Changelog.kt:31)
```

That points to https://github.com/JetBrains/gradle-changelog-plugin/blob/ca94e1d55e03b0959f4956497ba87a9c7d7e5ca2/src/main/kotlin/org/jetbrains/changelog/Changelog.kt#L31

**To Reproduce**
Apply Dokka 1.7.20 and run `patchChangelog` task.

**Expected behavior**
Task should pass.

**Environment:**
 - OS: Windows and Linux
 - Gradle Changelog Plugin Version: 1.3.1
 - Gradle Version: 7.5.1

**Comment by hsz** [comment]
Dokka bumped the `org.jetbrains:markdown` dependency to `0.3.1`, which contains some changes in class signatures. That causes an incorrect dependency version server for the Changelog plugin.
I've bumped it in this project to `0.3.1` – it'll be released soonish.

**Comment by xxfast** [comment]
Are there snapshot versions available anywhere now that address this issue?

**Comment by hsz** [comment]
There's already 2.0.0 released.
